# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4931ea63742027f8997b93fdcd0587eabf75c9f728721a316cc49df212d70b35c220d7048adaa887e9d938f8addb8c6000983de49c0d867490ac95944c43f294

test:
  secret_key_base: 3a5438728b49ca7dfb1dc47014c5dc2847750f4352d6a6aea525e124977c04c0d3aa1e73cea4b7618bb5f45862c13f2ddcbdf92827b3c3a7c231f865021d33b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
